name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t scrna-pipeline -f docker/Dockerfile .

    - name: Run Unit Tests inside Container
      run: docker run scrna-pipeline pytest tests/